# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436d1c332cda9eff39918a4e2985bc17c40c427fcb7f9c952fd968d5cabacd4584a838a4212c48613b5b103ee8fead835b30112825b6f6612ca24ef232a4184e

test:
  secret_key_base: 6ec0d9770bca9e597eeb7fd6c9a0746912a080e345e071a0b7e5ca12f110488bc540fd3f350e728e6e0d44c95f676bcc67dbe8968e7995cb384c3e0bd5262307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
